# Generated by Django 5.1.5 on 2025-01-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='le nom de la categorie', max_length=100, verbose_name='nom de la categorie')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='app.category', verbose_name='categorie du produit'),
        ),
    ]
