# Generated by Django 5.1.5 on 2025-01-28 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('status', models.CharField(choices=[('en attente', 'En Attente'), ('servi', 'Servi'), ('refuse', 'Refuse')], default='en attente', max_length=10)),
                ('date', models.DateField(verbose_name='date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='produit demandé')),
            ],
        ),
        migrations.CreateModel(
            name='en_attente',
            fields=[
            ],
            options={
                'verbose_name': 'demande en attente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.demande',),
        ),
        migrations.CreateModel(
            name='refuse',
            fields=[
            ],
            options={
                'verbose_name': 'demande refusée',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.demande',),
        ),
        migrations.CreateModel(
            name='servi',
            fields=[
            ],
            options={
                'verbose_name': 'demande servi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.demande',),
        ),
    ]
